// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Common.proto

package cmn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	RpcCode       *int32                 `protobuf:"varint,4,opt,name=rpc_code,json=rpcCode,proto3,oneof" json:"rpc_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_Common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_Common_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApiResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ApiResponse) GetRpcCode() int32 {
	if x != nil && x.RpcCode != nil {
		return *x.RpcCode
	}
	return 0
}

var File_Common_proto protoreflect.FileDescriptor

const file_Common_proto_rawDesc = "" +
	"\n" +
	"\fCommon.proto\x12\x13cn.mobile.ivy.proto\x1a\x19google/protobuf/any.proto\"\xa3\x01\n" +
	"\vApiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01\x12\x1e\n" +
	"\brpc_code\x18\x04 \x01(\x05H\x01R\arpcCode\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\v\n" +
	"\t_rpc_codeB\x1dP\x01Z\x19./internal/micros/cmn;cmnb\x06proto3"

var (
	file_Common_proto_rawDescOnce sync.Once
	file_Common_proto_rawDescData []byte
)

func file_Common_proto_rawDescGZIP() []byte {
	file_Common_proto_rawDescOnce.Do(func() {
		file_Common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Common_proto_rawDesc), len(file_Common_proto_rawDesc)))
	})
	return file_Common_proto_rawDescData
}

var file_Common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Common_proto_goTypes = []any{
	(*ApiResponse)(nil), // 0: cn.mobile.ivy.proto.ApiResponse
	(*anypb.Any)(nil),   // 1: google.protobuf.Any
}
var file_Common_proto_depIdxs = []int32{
	1, // 0: cn.mobile.ivy.proto.ApiResponse.data:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Common_proto_init() }
func file_Common_proto_init() {
	if File_Common_proto != nil {
		return
	}
	file_Common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Common_proto_rawDesc), len(file_Common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Common_proto_goTypes,
		DependencyIndexes: file_Common_proto_depIdxs,
		MessageInfos:      file_Common_proto_msgTypes,
	}.Build()
	File_Common_proto = out.File
	file_Common_proto_goTypes = nil
	file_Common_proto_depIdxs = nil
}
